config/routes.rb
Progress::Application.routes.draw do

  root :to => 'welcome#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  resources :sessions, except: :index
  resources :goals, only: [:index, :new, :create]

  resources :users, except: :index do
    resources :goals
    resources :micro_goals, only: :index
  end

  resources :goals do
    resources :micro_goals
  end

  resources :micro_goals do
    resources :proofs
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  first_name       :string(255)
#  last_name        :string(255)
#  email            :string(255)      not null
#  date_of_birth    :date
#  gender           :string(255)
#  crypted_password :string(255)
#  salt             :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  image            :string(255)
#  status           :string(255)
#  points           :integer
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :first_name, :last_name, :email, :date_of_birth, :gender, 
                  :password, :image, :remote_image_url

  validates :first_name, :last_name, :date_of_birth, :gender, :email, presence: true
  validates :email, uniqueness: true

  has_many :goals, dependent: :destroy
  has_many :micro_goals, through: :goals

  scope :new_users, where(:created_at => ((Date.today-7)..Date.today))

  mount_uploader :image, ImageUploader

  after_create :add_status
  after_create :initialize_points

  private

  def add_status
    self.status = "Fresh out of the gates"
    self.save
  end

  def initialize_points
    self.points = 0
    self.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      auto_login(@user)
      UserMailer.welcome_email(@user).deliver
      redirect_to new_goal_path
    else
      render :new, :alert => "Please try again"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<%= render "layouts/user_simpleform" %>

app/views/users/new.html.erb
<%= render "layouts/user_simpleform" %>

app/views/users/show.html.erb
<div>
  <h1 class="name"><%= "#{@user.first_name.upcase} #{@user.last_name.upcase}" %></h1>
</div>
<div class="edit">
  <%= link_to "Edit Profile", edit_user_path(@user), class: "edit-profile tiny button expand secondary" %>
</div>



<section class="small-4 large-8 columns">

  <fieldset class="user-status">
    <legend class="legend-border">Status</legend>
    <div class="small-6 large-6 columns status-center">
      Status: <%= @user.status %>
    </div>
    <div class="small-6 large-6 columns status-center">
      Points Achieved: <%= @user.points %>
    </div>
  </fieldset>

  <fieldset class="goal-list">
    <legend class="legend-border">My Goals</legend>
    <ul class="list-style-none">
      <% @user.goals.each do |goal| %>
        <li><%= link_to "#{goal.verb.capitalize} #{goal.title}", goal_path(goal.id), class: "small button float-left" %></li>
      <% end %>
    </ul>
  </fieldset>

</section>


<% @user.inspect %>