config/routes.rb
Progress::Application.routes.draw do

  root :to => 'welcome#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

  resources :sessions, except: :index
  resources :goals, only: [:index, :new, :create]

  resources :users, except: :index do
    resources :goals
    resources :micro_goals, only: :index
  end

  resources :goals do
    resources :micro_goals
  end

  resources :micro_goals do
    resources :proofs
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  

end

app/views/layouts/_goal_show.html.erb
<h2 class="goal-path">
  <%= "#{@goal.verb.capitalize} #{@goal.title}" %>
</h2>

<!-- <ul> -->
  <!-- <li>big-line</li> -->
  <!-- <li>add-microgoal button</li> -->
  <!-- <li>add-microgoal form modal</li> -->


<!-- </ul> -->

<ul class="steps">
  <li class="big-line">&nbsp;</li>
  <li><div class="add-microgoal">
    <a href="#" data-reveal-id="add-microgoal" class="success button expand microgoal">Add Microgoal</a></div>
  </li>
  <% @micro_goals.each do |m| %>
    <li class="big-line">&nbsp;</li>
    <% if m.completed == nil %>
      <!-- incompleted microgoal -->
      <li class="step-incomplete">
        <h6 class="title incomplete"><%= m.title.capitalize %></h6>
        <a href="#" data-reveal-id="add-proof" class="success done button tiny expand">Add Proof</a>
      </li>
      <li class="step-date"><%= m.completion_date.strftime("%A, %b, %e, %Y") %>
      </li> 
      <div id="add-proof" class="reveal-modal small">
        <%= render "layouts/proof_simpleform", :micro_goal => m %>
      </div>

    <% else %>
      <!-- completed microgoal -->
      <li class="step-complete">
        <h6 class="title"><%= m.title.capitalize %></h6>

        <div class="whole-completed-step">
          <%# if m.proof.lesson %>
          <div id="proof">
            <p class="lesson" <%= "id=#{m.proof.lesson}" %>>
              <%= m.proof.lesson %>
            </p>
            
            <%= image_tag m.proof.image.url(:proof), class: "proof-image" %>
          </div>
          <%= link_to "Details", '#', class: "secondary details button tiny expand" %>
        </div>
      </li>

    <% end %>
  <% end %>
</ul> 

app/views/layouts/_goal_simpleform.html.erb
<%= simple_form_for @goal, :html => { :class => "custom"} do |f| %>
  <div class="row">
    <div class="large-12 columns">
      <fieldset class="all-verbs">
        <legend><h3>I want to</h3></legend>
        <div class="row">
          <div class="large-12 columns">
            <% Goal::VERBS.each do |v| %>
            <div class="verb">
              <%= f.label v %>
              <%= f.radio_button :verb, v, class: "radio_button" %>
            </div>
            <% end %>
          </div>
        </div>
        
      <fieldset>
        <legend>Write the rest of your Goal</legend>
        <%= f.input :title, as: :text, size: 140, placeholder: "eg. French", 
       class: "text_field" %>
      </fieldset>

      </fieldset>

      <fieldset>
        <legend><h3>Why?</h3></legend>
        <%= f.input :motivation, as: :text, rows: 7, cols: 100 %>
      </fieldset>

      <fieldset>
        <legend><h3>When will you achieve this goal?</h3></legend>
        <%= f.input :completion_date, start_year: Time.now.year %>
      </fieldset>

      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/layouts/_login_modal.html.erb
<%= form_tag sessions_path, :method => :post do %>
  <div class="row">
    <div class="large-10 small-12 small-centered columns">
      <fieldset>
        <legend><h2>Log In</h2></legend>
        
        <div class="small-4 columns">
          <%= label_tag 'email', 'Email', :class => 'right inline' %>  
        </div>
        <div class="small-8 columns">
          <%= text_field_tag 'email' %>  
        </div>
        
        <div class="small-4 columns">
          <%= label_tag 'password', 'Password', :class => 'right inline' %>  
        </div>
        <div class="small-8 columns">
          <%= password_field_tag 'password' %>  
        </div>

        <div class="small-5 columns">
          <%= check_box_tag :remember_me, 1, params[:remember_me], :class => 'right inline' %>
        </div>
        <div class="small-7 columns">
          <%= label_tag :remember_me %>
        </div>
       
        <div class="small-4 columns"></div>
        <div class="small-8 columns">
          <%= submit_tag "Log in", :class => "tiny button" %>
        </div>
            
      </fieldset>
    </div>
  </div>
<% end %>

app/views/layouts/_microgoal_simpleform.html.erb
<%= form_for [@goal, @micro_goal], :html => { :class => "custom"} do |f| %>
  <fieldset>
    <legend><h3>How are you gonna do it?</h3></legend>
    <%= f.text_field :title, placeholder: "microgoal1", size: 100  %> By: <%= f.date_select :completion_date %>
  </fieldset>
  <%= f.button "add to your path" %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="fixed">
  <nav class="top-bar toggle-topbar">
    <ul class="title-area">
      <li class="name"><h1><%= link_to 'Progress', root_path, class: "title" %></h1></li>
      <li class="toggle-topbar">
        <a class="menu" href="#">Menu</a>
      </li>
    </ul>
   
    <section class="top-bar-section">
      <ul class="left">
        <li><%= link_to 'Add New Goal', new_goal_path, class: "new-goal" %></li>
      </ul>
      <ul class="right">
        <% if current_user %>
          <li class="has-dropdown">
            <%= link_to "#{current_user.first_name.capitalize}'s Profile", 
            user_path(current_user.id), class: "nav" %>
            <ul class="dropdown">
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li><%= link_to 'Logout', logout_path, class: 'logout' %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="#" data-reveal-id="signup-modal" class="signup">Sign Up</a></li>
          <li><a href="#" data-reveal-id="login-modal" class="login">Log In</a></li>
        <% end %>

        
      </ul>
      
    </section>
  </nav>
</div>

app/views/layouts/_proof_simpleform.html.erb
<div class="row">
  <div class="large-10 columns">
  
    <h1>Prove this step.</h1>
    <%= form_for [micro_goal, Proof.new], :html => { :class => "custom", multipart: true} do |f| %>
      <fieldset>
        <legend><h3><%= micro_goal.title %></h3></legend>

        <%= f.label :lesson, "Write about it:" %>
        <br>
        <%= f.text_area :lesson, placeholder: "140 characters or less" %>
        <br>
        <%= f.label :image, "Upload an image" %>
        <%= f.file_field :image %>
        <br>
        <%= f.label :remote_image_url, "or image URL" %><br/>
        <%= f.text_field :remote_image_url %>
        <br>
        <%= f.button %>    
      </fieldset>
    
    <% end %>
  </div>
</div>

app/views/layouts/_simpleform.html.erb
<%= simple_form_for @user, :html => { class: 'custom', multipart: true } do |f| %>      
  <div class="row">
    <div class="large-8">
      <fieldset><legend><h4>User Info</h4></legend>
        <%= f.input :first_name %>
        <br>
        <%= f.input :last_name %>
        <br>
        <%= f.input :email, placeholder: 'user@example.com' %>
        <br>
        <%= f.input :password %>
        <br>
        <div class="large-3">
          <%= f.input :gender, collection: [:male, :female] %>
        </div>
      </fieldset>
    </div>
  </div>

  <div class="row">
    <div class="large-8">
      <fieldset><legend><h4>Date of Birth</h4></legend>
        <div class="large-8">
          <%# f.input :date_of_birth, label: false, start_year: 1950, end_year: (Time.now).year %>  
          <%= f.input :date_of_birth %>
          
        </div>
      </fieldset>
    </div>
  </div>
  
  <div class="row">
    <div class="large-8">
      <fieldset> <legend><h4>Profile Picture</h4></legend>
        <%= f.input :image, label: "Profile Pic" %>
        <br>
        <h6>or</h6>
        <br>
        <%= f.input :remote_image_url, label: "link to image url" %>
        <br>
        <%= f.button :submit %>
      </fieldset>
    </div>
  </div>   
<% end %>

app/views/layouts/_user_simpleform.html.erb
<div class="row">
  <div class="large-12">

    <%= simple_form_for @user, 
    :html => { class: 'custom', multipart: true } do |f| %> 
      <fieldset class="user-info"><legend><h4>User Info</h4></legend>
        <fieldset class="user">
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :email, placeholder: 'user@example.com' %>
          <%= f.input :password %>
          <%= f.input :gender, collection: [:male, :female] %>
        </fieldset>
        <fieldset class="dob-profile">
          <%= f.input :date_of_birth, start_year: 1950 %>       
          <div class="create">
            <%= f.button :submit, class: "create" %>
          </div>

        </fieldset>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/_welcome.html.erb
<div class="welcome" style="background-color: #ccc; width: 100%; margin-top: -10px; padding: 50px; font-family: 'BebasNeue'">
      <h1 style="margin-left: 10%; padding: 15px; background-color: lightGreen; color: black; width: 30%; max-width: 50% text-shadow: 2px 2px white;">Progress</h1>
      <h4 style="margin-left: 10%; padding: 10px; width: 30%; color: black;
      background-color: tomato;">
        The proof is in the progress.
      </h4>

      <h5 style="margin-left: 17%; padding-top: 20px;">
        > Achieve your big goals
      </h5>
      <h5 style="margin-left: 17%; padding: 0;">
        > Break goals down into smaller steps.
      </h5>
      <h5 style="margin-left: 17%; padding: 0;">
        > Complete steps with proofs. 
      </h5>
      <h5 style="margin-left: 17%; padding: 0;">
        > Be self-accountable.

      </h5>
      <h5 style="margin-left: 17%; padding: 0;">
         > Stay self-motivated. 

      </h5>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Progress" %></title>
    <link href='http://fonts.googleapis.com/css?family=Montserrat|Arapey|Open+Sans:300italic,400,300' rel='stylesheet' type='text/css'>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% cache do %>
      <%= render "layouts/nav" %>  
    <% end %>
    <% if flash[:notice] %>
      <div class="alert-box">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert-box alert">
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>
    
    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>